import type { NextPage } from 'next';
import Head from 'next/head';

import useNaverMap from '../hooks/useNaverMap';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { map } = useNaverMap('naver-map');

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          type="text/javascript"
          src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=a8af1iim76"
          defer
        ></script>
      </Head>

      <div id="naver-map" style={{ height: '100vh', width: '100vw' }}></div>
    </div>
  );
};

export default Home;
