import type { GetServerSideProps, InferGetServerSidePropsType, NextPage } from 'next';
import Head from 'next/head';

import Header from '../components/Header';

type Post = {
  userId: number;
  id: number;
  title: string;
  body: string;
};

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/posts');
  const posts: Post[] = await res.json();

  return {
    props: {
      posts,
    },
  };
};

const Posts: NextPage = ({ posts }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          type="text/javascript"
          src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=a8af1iim76"
          defer
        ></script>
      </Head>
      <Header />
      <ul>
        {posts.map((post: Post) => (
          <li key={post.id}>{JSON.stringify(post)}</li>
        ))}
      </ul>
    </>
  );
};

export default Posts;
